project_id = "searce-playground"
environment = "dev"
#subnet1_region = "us-central1"
subnet1_zone = "us-central1-a"
#subnet1_cidr = "10.10.0.0/16"
subnet="rakhi-test-subnet"
network="mumbai-team-common-vpc"
