/**
 * Copyright 2020 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

pipeline {
  agent {
      label "terraform-exec"
  }
  stages {

 
    // [START tf-apply]
    stage('Test Project') {
      steps {
        container('terraform') {
          tpTestRun projectId: '3dSRL5Dq002tT6u9mFC1QQ', testId: 'mjp-mf6DG06AiOJ8e8fyqQ', agentId: 'osc2uxdFyE2zgGcn5sxD5Q', browser: 'Chrome', device: 'samsung-sm_n975w-RF8MA2SA5XR',  waitTestFinishSeconds: 180,  junitResultsFile: 'testResult.xml', executionParameters: ""
        }
      }
    }
    // [END tf-apply]
  }
}
